A1

Can the model accurately predict future negative or positive reviews?

A2

The objective is to build a neural network model to train and test a datset to predict new data. 

The goal is to able predict new data and scale it to larger datsets and this will allow to filter out the negative and positive reviews. Given the dataset is in text sentences.


A3

TensorFlow and Kera libraries are capable of performing text classification

B1

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [2]:
amazon_df = pd.read_csv('amazon_cells_labelled.txt', names = ['review', 'sentiments'], sep = '\t')
imdb_df = pd.read_csv('imdb_labelled.txt', names = ['review', 'sentiments'], sep = '\t')
yelp_df = pd.read_csv('yelp_labelled.txt', names = ['review', 'sentiments'], sep = '\t')

In [3]:
amazon_df

review  sentiments
0    So there is no way for me to plug it in here i...           0
1                          Good case, Excellent value.           1
2                               Great for the jawbone.           1
3    Tied to charger for conversations lasting more...           0
4                                    The mic is great.           1
..                                                 ...         ...
995  The screen does get smudged easily because it ...           0
996  What a piece of junk.. I lose more calls on th...           0
997                       Item Does Not Match Picture.           0
998  The only thing that disappoint me is the infra...           0
999  You can not answer calls with the unit, never ...           0

[1000 rows x 2 columns]

In [4]:
imdb_df

review  sentiments
0    A very, very, very slow-moving, aimless movie ...           0
1    Not sure who was more lost - the flat characte...           0
2    Attempting artiness with black & white and cle...           0
3         Very little music or anything to speak of.             0
4    The best scene in the movie was when Gerardo i...           1
..                                                 ...         ...
743  I just got bored watching Jessice Lange take h...           0
744  Unfortunately, any virtue in this film's produ...           0
745                   In a word, it is embarrassing.             0
746                               Exceptionally bad!             0
747  All in all its an insult to one's intelligence...           0

[748 rows x 2 columns]

In [5]:
yelp_df

review  sentiments
0                             Wow... Loved this place.           1
1                                   Crust is not good.           0
2            Not tasty and the texture was just nasty.           0
3    Stopped by during the late May bank holiday of...           1
4    The selection on the menu was great and so wer...           1
..                                                 ...         ...
995  I think food should have flavor and texture an...           0
996                           Appetite instantly gone.           0
997  Overall I was not impressed and would not go b...           0
998  The whole experience was underwhelming, and I ...           0
999  Then, as if I hadn't wasted enough of my life ...           0

[1000 rows x 2 columns]

In [6]:
imdb_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [7]:
amazon_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [8]:
yelp_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [9]:
amazon_df['sentiments'].unique()

array([0, 1], dtype=int64)

In [10]:
yelp_df['sentiments'].unique()

array([1, 0], dtype=int64)

In [11]:
imdb_df['sentiments'].unique()

array([0, 1], dtype=int64)

In [12]:
amazon_df['sentiments'].value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [13]:
imdb_df['sentiments'].value_counts()

1    386
0    362
Name: sentiments, dtype: int64

In [14]:
yelp_df['sentiments'].value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [15]:
amazon_df['review'].str.len()

0      82
1      27
2      22
3      79
4      17
       ..
995    72
996    55
997    28
998    63
999    58
Name: review, Length: 1000, dtype: int64

In [16]:
imdb_df['review'].str.len()

0       87
1       99
2      188
3       44
4      108
      ... 
743     63
744     92
745     32
746     20
747     75
Name: review, Length: 748, dtype: int64

In [17]:
yelp_df['review'].str.len()

0       24
1       18
2       41
3       87
4       59
      ... 
995     66
996     24
997     50
998     91
999    134
Name: review, Length: 1000, dtype: int64

In [18]:
print(min(amazon_df['review'].str.len()))
print(max(amazon_df['review'].str.len()))

11
149


In [19]:
print(min(imdb_df['review'].str.len()))
print(max(imdb_df['review'].str.len()))

7
8041


In [20]:
print(min(yelp_df['review'].str.len()))
print(max(yelp_df['review'].str.len()))

11
149


B2

B3

B4

B5

B6

C1

C2

C3

D1

D2

D3

D4

E

F

G

H

I

J