A1

Can the model accurately predict future negative or positive reviews?

A2

The objective is to build a neural network model to train and test a datset to predict new data. 

The goal is to able predict new data and scale it to larger datsets and this will allow to filter out the negative and positive reviews. Given the dataset is in text sentences.


A3

TensorFlow and Kera libraries are capable of performing text classification the type of neural network that performs this task is a recurrent neural network.

B1

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [109]:
amazon_df = pd.read_csv('amazon_cells_labelled.txt', names = ['review', 'sentiments'], sep = '\t')
imdb_df = pd.read_csv('imdb_labelled.txt', names = ['review', 'sentiments'], sep = '\t')
yelp_df = pd.read_csv('yelp_labelled.txt', names = ['review', 'sentiments'], sep = '\t')

In [3]:
amazon_df

review  sentiments
0    So there is no way for me to plug it in here i...           0
1                          Good case, Excellent value.           1
2                               Great for the jawbone.           1
3    Tied to charger for conversations lasting more...           0
4                                    The mic is great.           1
..                                                 ...         ...
995  The screen does get smudged easily because it ...           0
996  What a piece of junk.. I lose more calls on th...           0
997                       Item Does Not Match Picture.           0
998  The only thing that disappoint me is the infra...           0
999  You can not answer calls with the unit, never ...           0

[1000 rows x 2 columns]

In [110]:
imdb_df

review  sentiments
0    A very, very, very slow-moving, aimless movie ...           0
1    Not sure who was more lost - the flat characte...           0
2    Attempting artiness with black & white and cle...           0
3         Very little music or anything to speak of.             0
4    The best scene in the movie was when Gerardo i...           1
..                                                 ...         ...
743  I just got bored watching Jessice Lange take h...           0
744  Unfortunately, any virtue in this film's produ...           0
745                   In a word, it is embarrassing.             0
746                               Exceptionally bad!             0
747  All in all its an insult to one's intelligence...           0

[748 rows x 2 columns]

In [5]:
yelp_df

review  sentiments
0                             Wow... Loved this place.           1
1                                   Crust is not good.           0
2            Not tasty and the texture was just nasty.           0
3    Stopped by during the late May bank holiday of...           1
4    The selection on the menu was great and so wer...           1
..                                                 ...         ...
995  I think food should have flavor and texture an...           0
996                           Appetite instantly gone.           0
997  Overall I was not impressed and would not go b...           0
998  The whole experience was underwhelming, and I ...           0
999  Then, as if I hadn't wasted enough of my life ...           0

[1000 rows x 2 columns]

In [6]:
imdb_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [7]:
amazon_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [8]:
yelp_df.isnull().sum()

review        0
sentiments    0
dtype: int64

In [9]:
amazon_df['sentiments'].unique()

array([0, 1], dtype=int64)

In [10]:
yelp_df['sentiments'].unique()

array([1, 0], dtype=int64)

In [11]:
imdb_df['sentiments'].unique()

array([0, 1], dtype=int64)

In [12]:
amazon_df['sentiments'].value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [13]:
imdb_df['sentiments'].value_counts()

1    386
0    362
Name: sentiments, dtype: int64

In [14]:
yelp_df['sentiments'].value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [15]:
amazon_df['review'].str.len()

0      82
1      27
2      22
3      79
4      17
       ..
995    72
996    55
997    28
998    63
999    58
Name: review, Length: 1000, dtype: int64

In [16]:
imdb_df['review'].str.len()

0       87
1       99
2      188
3       44
4      108
      ... 
743     63
744     92
745     32
746     20
747     75
Name: review, Length: 748, dtype: int64

In [17]:
yelp_df['review'].str.len()

0       24
1       18
2       41
3       87
4       59
      ... 
995     66
996     24
997     50
998     91
999    134
Name: review, Length: 1000, dtype: int64

In [18]:
print(min(amazon_df['review'].str.len()))
print(max(amazon_df['review'].str.len()))

11
149


In [19]:
print(min(imdb_df['review'].str.len()))
print(max(imdb_df['review'].str.len()))

7
7944


In [20]:
print(min(yelp_df['review'].str.len()))
print(max(yelp_df['review'].str.len()))

11
149


In [21]:
amazon_df.sentiments.value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [22]:
imdb_df.sentiments.value_counts()

1    386
0    362
Name: sentiments, dtype: int64

In [23]:
yelp_df.sentiments.value_counts()

1    500
0    500
Name: sentiments, dtype: int64

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
count_vectorize = CountVectorizer()

In [35]:
feature_vector_amazon = count_vectorize.fit(amazon_df.review)

In [37]:
features_amazon = feature_vector_amazon.get_feature_names()

In [63]:
print('amazon total number of unique words:', len(features_amazon))

amazon total number of unique words: 1847


In [45]:
feature_vector_yelp = count_vectorize.fit(yelp_df.review)

In [46]:
features_yelp = feature_vector_yelp.get_feature_names()

In [62]:
print('yelp total number of unique words:', len(features_yelp))

yelp total number of unique words: 2035


In [56]:
feature_vector_imdb = count_vectorize.fit(imdb_df.review)

In [57]:
features_imdb = feature_vector_imdb.get_feature_names()

In [61]:
print('imdb total number of unique words:', len(features_imdb))

imdb total number of unique words: 3047


In [72]:
import random

In [90]:
random.sample(features, 10)

['flawless',
 'took',
 'low',
 'difficult',
 'ideal',
 'best',
 'at',
 'tv',
 'pcs',
 'major']

In [97]:
# create dataframes
import pandas as pd

# amazon
amazon = open('amazon_cells_labelled.txt').read()

a_labels, a_texts = [], []
for i, line in enumerate(amazon.split('\n')):
    content = line.split('\t')
    if len(content) > 1:
        a_texts.append(content[0])
        a_labels.append(content[1])

df_a = pd.DataFrame()
df_a['label'] = a_labels
df_a['text'] = a_texts
df_a['source'] = 'amazon'

# imdb
imdb = open('imdb_labelled.txt').read()

i_labels, i_texts = [], []
for i, line in enumerate(imdb.split('\n')):
    content = line.split('\t')
    if len(content) > 1:
        i_texts.append(content[0])
        i_labels.append(content[1])

df_i = pd.DataFrame()
df_i['label'] = i_labels
df_i['text'] = i_texts
df_i['source'] = 'imdb'

# yelp
yelp = open('yelp_labelled.txt').read()

y_labels, y_texts = [], []
for i, line in enumerate(yelp.split('\n')):
    content = line.split('\t')
    if len(content) > 1:
        y_texts.append(content[0])
        y_labels.append(content[1])

df_y = pd.DataFrame()
df_y['label'] = y_labels
df_y['text'] = y_texts
df_y['source'] = 'yelp'

In [100]:
# preview 
display(df_a.head())
display(df_a.shape)
display(df_i.head())
display(df_i.shape)
display(df_y.head())
display(df_y.shape)

label                                               text  source
0     0  So there is no way for me to plug it in here i...  amazon
1     1                        Good case, Excellent value.  amazon
2     1                             Great for the jawbone.  amazon
3     0  Tied to charger for conversations lasting more...  amazon
4     1                                  The mic is great.  amazon

(1000, 3)

label                                               text source
0     0  A very, very, very slow-moving, aimless movie ...   imdb
1     0  Not sure who was more lost - the flat characte...   imdb
2     0  Attempting artiness with black & white and cle...   imdb
3     0       Very little music or anything to speak of.     imdb
4     1  The best scene in the movie was when Gerardo i...   imdb

(1000, 3)

label                                               text source
0     1                           Wow... Loved this place.   yelp
1     0                                 Crust is not good.   yelp
2     0          Not tasty and the texture was just nasty.   yelp
3     1  Stopped by during the late May bank holiday of...   yelp
4     1  The selection on the menu was great and so wer...   yelp

(1000, 3)

In [102]:
# combine site dataframes
df = pd.concat([df_a, df_i, df_y], ignore_index=True)
df.label = df.label.astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   3000 non-null   int32 
 1   text    3000 non-null   object
 2   source  3000 non-null   object
dtypes: int32(1), object(2)
memory usage: 58.7+ KB


In [103]:
df

label                                               text  source
0         0  So there is no way for me to plug it in here i...  amazon
1         1                        Good case, Excellent value.  amazon
2         1                             Great for the jawbone.  amazon
3         0  Tied to charger for conversations lasting more...  amazon
4         1                                  The mic is great.  amazon
...     ...                                                ...     ...
2995      0  I think food should have flavor and texture an...    yelp
2996      0                           Appetite instantly gone.    yelp
2997      0  Overall I was not impressed and would not go b...    yelp
2998      0  The whole experience was underwhelming, and I ...    yelp
2999      0  Then, as if I hadn't wasted enough of my life ...    yelp

[3000 rows x 3 columns]

B2

B3

B4

B5

B6

C1

C2

C3

D1

D2

D3

D4

E

F

G

H

I

J